nav:
  - Syntax: syntax.md
  - Variabler: variables.md
  - Selektion: selection.md
  - Kodblock: codeblocks.md
  - Iteration: iteration.md
  - Operatorer: operators.md
  - Uttryck: expressions.md
  - Statements: statements.md
  - Metoder: methods.md