nav:
  - Planering: 
    - index.md
    - Kategorier: categories.md
    - Examination: examination
    - Kurser: kurser
    - Extra övningar: extra
  - Material:
    - material/index.md
    - Allmänt: material/general
    - C#: material/cs
    - SQL: material/sql
    - Övrigt: material/misc
