nav:
  - Lektioner: 
    - index.md
    - moment.md
    - Kategorier: categories.md
    - examination 
    - Veckor: lektioner
    - Extar övningar: extra
  - Material:
    - material/index.md
    - Allmänt: material/general
    - C#: material/cs
    - SQL: material/sql
    - Övrigt: material/misc
