nav:
  - Lektioner: 
    - index.md
    - moment.md
    - Kategorier: categories.md
    - examination 
    - Veckor: lektioner
  - Material:
    - material/index.md
    - Allmänt: material/general
    - C#: material/cs
    - material/git
    - Testning: material/testing
    - Övrigt: material/misc
