nav:
  - Lektion 3: kurser/oop1/intro/v01/lektion 3/index.md
  - Övning 03 Pseudokod: pseudocode.md
  - Övning 03 String: strings.md
  - Övning 03 File: fileandstring.md
  - Övning 03 Random: random.md