name: ci
on:
  push:
    branches: [ master, main ]
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'   # safer for MkDocs plugins
          cache: 'pip'

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      # Keep Material's build cache (optional but fine)
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: ~/.cache
          restore-keys: |
            mkdocs-material-

      - run: pip install -r requirements.txt

      # Fail fast on config/content issues
      - run: mkdocs build --strict

      - run: mkdocs gh-deploy --force
