nav:
  - Lektion 3: lektioner/intro/v. 1 Intro/lektion 3/index.md
  - Övning 1 - Pseudokod: exercises.md
  - Övning 2 - String: strings.md
  - Övning 3 - File: fileandstring.md
  - Övning 4 - Random: random.md