nav:
  - Lektion 3: lektioner/intro/v. 1 Intro/lektion 3/index.md
  - Övning 03 Pseudokod: pseudocode.md
  - Övning 03 String: strings.md
  - Övning 03 File: fileandstring.md
  - Övning 03 Random: random.md