nav:
  - Lektion 3: lektioner/intro/v. 1 Intro/lektion 3/index.md
  - Övning - Pseudokod: pseudocode.md
  - Övning - String: strings.md
  - Övning - File: fileandstring.md
  - Övning - Random: random.md